baseurl = "http://psilocene.org"
languageCode = "en-us"
title = "psilocene"
theme = "cene"

pluralizeListTitles = false
[params]
Description = "a new epoch in which humanity returns to harmony with itself and nature by stripping away the darkness within"
Analytics = "UA-70341821-1"
discourseUrl = "http://forum.psilocene.org"
[params.links]
foundation = "/foundation"
druglog = "/collective/druglog"
collective = "/collective"
[params.external]
forum = "http://forum.psilocene.org"
[params.resources]
links = "/portal/links"
information = "/portal/information"
podcasts = "/portal/podcasts"
blogs = "/portal/blogs"
communities = "/portal/communities"
