baseurl = "http://psilocene.org"
languageCode = "en-us"
title = "psilocene"
theme = "psilocene"
disqusShortname = "psilocene"
pluralizeListTitles = false
[params]
Description = "a new period in which humanity returns to harmony with itself and nature, stripping away the dogma and hatred within"
Analytics = "UA-70341821-1"
[params.links]
foundation = "/foundation"
druglog = "/collective/druglog"
collective = "/collective"
