baseurl = "http://psilocene.org"
languageCode = "en-us"
title = "psilocene"
theme = "cene"

pluralizeListTitles = false
[params]
Description = "a new epoch in which humanity returns to harmony with itself and nature"
Analytics = "UA-70341821-1"
discourseUrl = "http://forum.psilocene.org/"
[params.links]
druglog = "/collective/druglog"
collective = "/collective"
[params.external]
[params.registry]
podcasts = "/registry/podcasts"
